// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Birthday struct {
	ID          int64
	DiscordUuid string
	Day         int64
	Month       int64
}

type Player struct {
	ID          int64
	McUuid      string
	McUsername  string
	DiscordUuid string
	Country     string
	InvitedBy   string
	Whitelisted bool
	LeftServer  bool
}
