// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (
    mc_uuid, mc_username, discord_uuid, whitelisted
) VALUES (
    ?, ?, ?, ?
) RETURNING id, mc_uuid, mc_username, discord_uuid, country, invited_by, whitelisted, left_server
`

type CreatePlayerParams struct {
	McUuid      string
	McUsername  string
	DiscordUuid string
	Whitelisted bool
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.McUuid,
		arg.McUsername,
		arg.DiscordUuid,
		arg.Whitelisted,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.McUuid,
		&i.McUsername,
		&i.DiscordUuid,
		&i.Country,
		&i.InvitedBy,
		&i.Whitelisted,
		&i.LeftServer,
	)
	return i, err
}

const getPlayerByDiscordUuid = `-- name: GetPlayerByDiscordUuid :one
SELECT id, mc_uuid, mc_username, discord_uuid, country, invited_by, whitelisted, left_server FROM players
WHERE discord_uuid = ?
`

func (q *Queries) GetPlayerByDiscordUuid(ctx context.Context, discordUuid string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByDiscordUuid, discordUuid)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.McUuid,
		&i.McUsername,
		&i.DiscordUuid,
		&i.Country,
		&i.InvitedBy,
		&i.Whitelisted,
		&i.LeftServer,
	)
	return i, err
}
